### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by drcrypter2007** [emmaroebreeden/Lucas#1]
leave kant alone, there's legit no reason to start shit with him, so what if he rats, let him be bruh
grow up

**Comment by emmaroebreeden** [comment]
https://github.com/GardeningTool/HostsMod/issues/79

**Comment by drcrypter2007** [comment]
???

**Comment by emmaroebreeden** [comment]
u cannot say "grow up" when u legit are doing the same thing
all im doing is making sure kant gets credit for his work
also he is doing more than rats hence "Free andre!" being his bio

**Comment by drcrypter2007** [comment]
not doing the same thing
andre isn't his "bro" anymore, you have no idea what even happens because you're some 14 year old 2020 newfag

**Comment by emmaroebreeden** [comment]
u legit are tho u must be retarded if u dont think so
doesnt matter whose into who doesnt change that its more than ratting if i cared about ratting i wouldnt have only kant here
unless u have something else dont bother responding

**Comment by jeremypelletier** [comment]
https://cdn.discordapp.com/attachments/955137306447208448/959621352275451904/IMG_5742.MOV

**Comment by 0xa00** [comment]
> u legit are tho u must be retarded if u dont think so doesnt matter whose into who doesnt change that its more than ratting if i cared about ratting i wouldnt have only kant here unless u have something else dont bother responding

low iq personality

**Comment by 0xa00** [comment]
> not doing the same thing andre isn't his "bro" anymore, you have no idea what even happens because you're some 14 year old 2020 newfag

low iq issue

**Comment by drcrypter2007** [comment]
> u legit are tho u must be retarded if u dont think so doesnt matter whose into who doesnt change that its more than ratting if i cared about ratting i wouldnt have only kant here unless u have something else dont bother responding

low iq issue
